/*
 *  Phusion Passenger - https://www.phusionpassenger.com/
 *  Copyright (c) 2010-2017 Phusion Holding B.V.
 *
 *  "Passenger", "Phusion Passenger" and "Union Station" are registered
 *  trademarks of Phusion Holding B.V.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in
 *  all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *  THE SOFTWARE.
 */

/*
 * LocationConfig/AutoGeneratedTrackFunction.c is automatically generated from
 * LocationConfig/AutoGeneratedTrackFunction.c.cxxcodebuilder,
 * using definitions from src/ruby_supportlib/phusion_passenger/nginx/config_options.rb.
 * Edits to LocationConfig/AutoGeneratedTrackFunction.c will be lost.
 *
 * To update LocationConfig/AutoGeneratedTrackFunction.c:
 *   rake nginx
 *
 * To force regeneration of LocationConfig/AutoGeneratedTrackFunction.c:
 *   rm -f src/nginx_module/LocationConfig/AutoGeneratedTrackFunction.c
 *   rake src/nginx_module/LocationConfig/AutoGeneratedTrackFunction.c
 */

void
passenger_track_autogenerated_loc_conf(postprocess_ctx_t *ctx, passenger_loc_conf_t *conf, ngx_http_core_srv_conf_t *cscf, ngx_http_core_loc_conf_t *clcf, ngx_str_t *app_group_name) {
    PsgJsonValue *entry, *hierarchy_member;

    if (conf->autogenerated.enabled_explicitly_set) {
        entry = find_or_create_manifest_location_config_entry(ctx,
            app_group_name, cscf, clcf,
            "passenger_enabled",
            sizeof("passenger_enabled") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.enabled_source_file,
            conf->autogenerated.enabled_source_line);
        psg_json_value_set_bool(hierarchy_member, "value",
            conf->autogenerated.enabled);
    }
    if (conf->autogenerated.ruby_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_ruby",
            sizeof("passenger_ruby") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.ruby_source_file,
            conf->autogenerated.ruby_source_line);
        psg_json_value_set_str(hierarchy_member, "value",
            (const char *) conf->autogenerated.ruby.data,
            conf->autogenerated.ruby.len);
    }
    if (conf->autogenerated.python_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_python",
            sizeof("passenger_python") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.python_source_file,
            conf->autogenerated.python_source_line);
        psg_json_value_set_str(hierarchy_member, "value",
            (const char *) conf->autogenerated.python.data,
            conf->autogenerated.python.len);
    }
    if (conf->autogenerated.nodejs_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_nodejs",
            sizeof("passenger_nodejs") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.nodejs_source_file,
            conf->autogenerated.nodejs_source_line);
        psg_json_value_set_str(hierarchy_member, "value",
            (const char *) conf->autogenerated.nodejs.data,
            conf->autogenerated.nodejs.len);
    }
    if (conf->autogenerated.meteor_app_settings_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_meteor_app_settings",
            sizeof("passenger_meteor_app_settings") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.meteor_app_settings_source_file,
            conf->autogenerated.meteor_app_settings_source_line);
        psg_json_value_set_str(hierarchy_member, "value",
            (const char *) conf->autogenerated.meteor_app_settings.data,
            conf->autogenerated.meteor_app_settings.len);
    }
    if (conf->autogenerated.environment_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_app_env",
            sizeof("passenger_app_env") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.environment_source_file,
            conf->autogenerated.environment_source_line);
        psg_json_value_set_str(hierarchy_member, "value",
            (const char *) conf->autogenerated.environment.data,
            conf->autogenerated.environment.len);
    }
    if (conf->autogenerated.friendly_error_pages_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_friendly_error_pages",
            sizeof("passenger_friendly_error_pages") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.friendly_error_pages_source_file,
            conf->autogenerated.friendly_error_pages_source_line);
        psg_json_value_set_bool(hierarchy_member, "value",
            conf->autogenerated.friendly_error_pages);
    }
    if (conf->autogenerated.min_instances_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_min_instances",
            sizeof("passenger_min_instances") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.min_instances_source_file,
            conf->autogenerated.min_instances_source_line);
        psg_json_value_set_uint(hierarchy_member, "value",
            conf->autogenerated.min_instances);
    }
    if (conf->autogenerated.max_requests_explicitly_set) {
        entry = find_or_create_manifest_location_config_entry(ctx,
            app_group_name, cscf, clcf,
            "passenger_max_requests",
            sizeof("passenger_max_requests") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.max_requests_source_file,
            conf->autogenerated.max_requests_source_line);
        psg_json_value_set_uint(hierarchy_member, "value",
            conf->autogenerated.max_requests);
    }
    if (conf->autogenerated.start_timeout_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_start_timeout",
            sizeof("passenger_start_timeout") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.start_timeout_source_file,
            conf->autogenerated.start_timeout_source_line);
        psg_json_value_set_int(hierarchy_member, "value",
            conf->autogenerated.start_timeout);
    }
    if (conf->autogenerated.base_uris_explicitly_set) {
        entry = find_or_create_manifest_location_config_entry(ctx,
            app_group_name, cscf, clcf,
            "passenger_base_uri",
            sizeof("passenger_base_uri") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.base_uris_source_file,
            conf->autogenerated.base_uris_source_line);
        psg_json_value_set_str_array(hierarchy_member, "value",
            conf->autogenerated.base_uris);
    }
    if (conf->autogenerated.document_root_explicitly_set) {
        entry = find_or_create_manifest_location_config_entry(ctx,
            app_group_name, cscf, clcf,
            "passenger_document_root",
            sizeof("passenger_document_root") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.document_root_source_file,
            conf->autogenerated.document_root_source_line);
        psg_json_value_set_str(hierarchy_member, "value",
            (const char *) conf->autogenerated.document_root.data,
            conf->autogenerated.document_root.len);
    }
    if (conf->autogenerated.user_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_user",
            sizeof("passenger_user") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.user_source_file,
            conf->autogenerated.user_source_line);
        psg_json_value_set_str(hierarchy_member, "value",
            (const char *) conf->autogenerated.user.data,
            conf->autogenerated.user.len);
    }
    if (conf->autogenerated.group_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_group",
            sizeof("passenger_group") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.group_source_file,
            conf->autogenerated.group_source_line);
        psg_json_value_set_str(hierarchy_member, "value",
            (const char *) conf->autogenerated.group.data,
            conf->autogenerated.group.len);
    }
    if (conf->autogenerated.app_group_name_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_app_group_name",
            sizeof("passenger_app_group_name") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.app_group_name_source_file,
            conf->autogenerated.app_group_name_source_line);
        psg_json_value_set_str(hierarchy_member, "value",
            (const char *) conf->autogenerated.app_group_name.data,
            conf->autogenerated.app_group_name.len);
    }
    if (conf->autogenerated.app_root_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_app_root",
            sizeof("passenger_app_root") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.app_root_source_file,
            conf->autogenerated.app_root_source_line);
        psg_json_value_set_str(hierarchy_member, "value",
            (const char *) conf->autogenerated.app_root.data,
            conf->autogenerated.app_root.len);
    }
    if (conf->autogenerated.app_rights_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_app_rights",
            sizeof("passenger_app_rights") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.app_rights_source_file,
            conf->autogenerated.app_rights_source_line);
        psg_json_value_set_str(hierarchy_member, "value",
            (const char *) conf->autogenerated.app_rights.data,
            conf->autogenerated.app_rights.len);
    }
    if (conf->autogenerated.debugger_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_debugger",
            sizeof("passenger_debugger") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.debugger_source_file,
            conf->autogenerated.debugger_source_line);
        psg_json_value_set_bool(hierarchy_member, "value",
            conf->autogenerated.debugger);
    }
    if (conf->autogenerated.max_preloader_idle_time_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_max_preloader_idle_time",
            sizeof("passenger_max_preloader_idle_time") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.max_preloader_idle_time_source_file,
            conf->autogenerated.max_preloader_idle_time_source_line);
        psg_json_value_set_int(hierarchy_member, "value",
            conf->autogenerated.max_preloader_idle_time);
    }
    if (conf->autogenerated.env_vars_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_env_var",
            sizeof("passenger_env_var") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.env_vars_source_file,
            conf->autogenerated.env_vars_source_line);
        psg_json_value_set_str_keyval(hierarchy_member, "value",
            conf->autogenerated.env_vars);
    }
    if (conf->autogenerated.headers_source_explicitly_set) {
        entry = find_or_create_manifest_location_config_entry(ctx,
            app_group_name, cscf, clcf,
            "passenger_set_header",
            sizeof("passenger_set_header") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.headers_source_source_file,
            conf->autogenerated.headers_source_source_line);
        psg_json_value_set_str_keyval(hierarchy_member, "value",
            conf->autogenerated.headers_source);
    }
    if (conf->autogenerated.upstream_config_pass_headers_explicitly_set) {
        entry = find_or_create_manifest_location_config_entry(ctx,
            app_group_name, cscf, clcf,
            "passenger_pass_header",
            sizeof("passenger_pass_header") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.upstream_config_pass_headers_source_file,
            conf->autogenerated.upstream_config_pass_headers_source_line);
        psg_json_value_set_str_array(hierarchy_member, "value",
            conf->upstream_config.pass_headers);
    }
    if (conf->autogenerated.headers_hash_max_size_explicitly_set) {
        entry = find_or_create_manifest_location_config_entry(ctx,
            app_group_name, cscf, clcf,
            "passenger_headers_hash_max_size",
            sizeof("passenger_headers_hash_max_size") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.headers_hash_max_size_source_file,
            conf->autogenerated.headers_hash_max_size_source_line);
        psg_json_value_set_uint(hierarchy_member, "value",
            conf->autogenerated.headers_hash_max_size);
    }
    if (conf->autogenerated.headers_hash_bucket_size_explicitly_set) {
        entry = find_or_create_manifest_location_config_entry(ctx,
            app_group_name, cscf, clcf,
            "passenger_headers_hash_bucket_size",
            sizeof("passenger_headers_hash_bucket_size") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.headers_hash_bucket_size_source_file,
            conf->autogenerated.headers_hash_bucket_size_source_line);
        psg_json_value_set_uint(hierarchy_member, "value",
            conf->autogenerated.headers_hash_bucket_size);
    }
    if (conf->autogenerated.upstream_config_ignore_client_abort_explicitly_set) {
        entry = find_or_create_manifest_location_config_entry(ctx,
            app_group_name, cscf, clcf,
            "passenger_ignore_client_abort",
            sizeof("passenger_ignore_client_abort") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.upstream_config_ignore_client_abort_source_file,
            conf->autogenerated.upstream_config_ignore_client_abort_source_line);
        psg_json_value_set_bool(hierarchy_member, "value",
            conf->upstream_config.ignore_client_abort);
    }
    if (conf->autogenerated.upstream_config_read_timeout_explicitly_set) {
        entry = find_or_create_manifest_location_config_entry(ctx,
            app_group_name, cscf, clcf,
            "passenger_read_timeout",
            sizeof("passenger_read_timeout") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.upstream_config_read_timeout_source_file,
            conf->autogenerated.upstream_config_read_timeout_source_line);
        psg_json_value_set_uint(hierarchy_member, "value",
            conf->upstream_config.read_timeout);
    }
    if (conf->autogenerated.upstream_config_buffering_explicitly_set) {
        entry = find_or_create_manifest_location_config_entry(ctx,
            app_group_name, cscf, clcf,
            "passenger_buffer_response",
            sizeof("passenger_buffer_response") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.upstream_config_buffering_source_file,
            conf->autogenerated.upstream_config_buffering_source_line);
        psg_json_value_set_bool(hierarchy_member, "value",
            conf->upstream_config.buffering);
    }
    if (conf->autogenerated.upstream_config_intercept_errors_explicitly_set) {
        entry = find_or_create_manifest_location_config_entry(ctx,
            app_group_name, cscf, clcf,
            "passenger_intercept_errors",
            sizeof("passenger_intercept_errors") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.upstream_config_intercept_errors_source_file,
            conf->autogenerated.upstream_config_intercept_errors_source_line);
        psg_json_value_set_bool(hierarchy_member, "value",
            conf->upstream_config.intercept_errors);
    }
    if (conf->autogenerated.spawn_method_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_spawn_method",
            sizeof("passenger_spawn_method") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.spawn_method_source_file,
            conf->autogenerated.spawn_method_source_line);
        psg_json_value_set_str(hierarchy_member, "value",
            (const char *) conf->autogenerated.spawn_method.data,
            conf->autogenerated.spawn_method.len);
    }
    if (conf->autogenerated.load_shell_envvars_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_load_shell_envvars",
            sizeof("passenger_load_shell_envvars") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.load_shell_envvars_source_file,
            conf->autogenerated.load_shell_envvars_source_line);
        psg_json_value_set_bool(hierarchy_member, "value",
            conf->autogenerated.load_shell_envvars);
    }
    if (conf->autogenerated.max_request_queue_size_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_max_request_queue_size",
            sizeof("passenger_max_request_queue_size") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.max_request_queue_size_source_file,
            conf->autogenerated.max_request_queue_size_source_line);
        psg_json_value_set_uint(hierarchy_member, "value",
            conf->autogenerated.max_request_queue_size);
    }
    if (conf->autogenerated.request_queue_overflow_status_code_explicitly_set) {
        entry = find_or_create_manifest_location_config_entry(ctx,
            app_group_name, cscf, clcf,
            "passenger_request_queue_overflow_status_code",
            sizeof("passenger_request_queue_overflow_status_code") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.request_queue_overflow_status_code_source_file,
            conf->autogenerated.request_queue_overflow_status_code_source_line);
        psg_json_value_set_int(hierarchy_member, "value",
            conf->autogenerated.request_queue_overflow_status_code);
    }
    if (conf->autogenerated.restart_dir_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_restart_dir",
            sizeof("passenger_restart_dir") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.restart_dir_source_file,
            conf->autogenerated.restart_dir_source_line);
        psg_json_value_set_str(hierarchy_member, "value",
            (const char *) conf->autogenerated.restart_dir.data,
            conf->autogenerated.restart_dir.len);
    }
    if (conf->autogenerated.app_type_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_app_type",
            sizeof("passenger_app_type") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.app_type_source_file,
            conf->autogenerated.app_type_source_line);
        psg_json_value_set_str(hierarchy_member, "value",
            (const char *) conf->autogenerated.app_type.data,
            conf->autogenerated.app_type.len);
    }
    if (conf->autogenerated.startup_file_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_startup_file",
            sizeof("passenger_startup_file") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.startup_file_source_file,
            conf->autogenerated.startup_file_source_line);
        psg_json_value_set_str(hierarchy_member, "value",
            (const char *) conf->autogenerated.startup_file.data,
            conf->autogenerated.startup_file.len);
    }
    if (conf->autogenerated.sticky_sessions_explicitly_set) {
        entry = find_or_create_manifest_location_config_entry(ctx,
            app_group_name, cscf, clcf,
            "passenger_sticky_sessions",
            sizeof("passenger_sticky_sessions") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.sticky_sessions_source_file,
            conf->autogenerated.sticky_sessions_source_line);
        psg_json_value_set_bool(hierarchy_member, "value",
            conf->autogenerated.sticky_sessions);
    }
    if (conf->autogenerated.sticky_sessions_cookie_name_explicitly_set) {
        entry = find_or_create_manifest_location_config_entry(ctx,
            app_group_name, cscf, clcf,
            "passenger_sticky_sessions_cookie_name",
            sizeof("passenger_sticky_sessions_cookie_name") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.sticky_sessions_cookie_name_source_file,
            conf->autogenerated.sticky_sessions_cookie_name_source_line);
        psg_json_value_set_str(hierarchy_member, "value",
            (const char *) conf->autogenerated.sticky_sessions_cookie_name.data,
            conf->autogenerated.sticky_sessions_cookie_name.len);
    }
    if (conf->autogenerated.vary_turbocache_by_cookie_explicitly_set) {
        entry = find_or_create_manifest_location_config_entry(ctx,
            app_group_name, cscf, clcf,
            "passenger_vary_turbocache_by_cookie",
            sizeof("passenger_vary_turbocache_by_cookie") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.vary_turbocache_by_cookie_source_file,
            conf->autogenerated.vary_turbocache_by_cookie_source_line);
        psg_json_value_set_str(hierarchy_member, "value",
            (const char *) conf->autogenerated.vary_turbocache_by_cookie.data,
            conf->autogenerated.vary_turbocache_by_cookie.len);
    }
    if (conf->autogenerated.abort_websockets_on_process_shutdown_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_abort_websockets_on_process_shutdown",
            sizeof("passenger_abort_websockets_on_process_shutdown") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.abort_websockets_on_process_shutdown_source_file,
            conf->autogenerated.abort_websockets_on_process_shutdown_source_line);
        psg_json_value_set_bool(hierarchy_member, "value",
            conf->autogenerated.abort_websockets_on_process_shutdown);
    }
    if (conf->autogenerated.force_max_concurrent_requests_per_process_explicitly_set) {
        entry = find_or_create_manifest_application_config_entry(ctx,
            app_group_name,
            "passenger_force_max_concurrent_requests_per_process",
            sizeof("passenger_force_max_concurrent_requests_per_process") - 1);
        hierarchy_member = add_manifest_config_option_hierarchy_member(entry,
            &conf->autogenerated.force_max_concurrent_requests_per_process_source_file,
            conf->autogenerated.force_max_concurrent_requests_per_process_source_line);
        psg_json_value_set_int(hierarchy_member, "value",
            conf->autogenerated.force_max_concurrent_requests_per_process);
    }

    /*
     * No autogenerated code for:
     * passenger_ignore_headers
     * passenger_buffer_size
     * passenger_buffers
     * passenger_busy_buffers_size
     */
}

